.PHONY: iteration1 iteration2 iteration3

all:
	#$(MAKE) -C iteration1
	#$(MAKE) -C iteration2
	$(MAKE) -C iteration3

clean:
	$(MAKE) -C iteration1 clean
	$(MAKE) -C iteration2 clean
	$(MAKE) -C iteration3 clean
